# Generated by Django 5.0.2 on 2024-02-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('Age', models.IntegerField()),
                ('Department', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='student/img')),
            ],
        ),
    ]
